### ISSUE TITLE
Node status not updating

### ISSUE THREAD

**Issue by jerbzz** [huzergackl/node-red-contrib-time-switch#11]
**Describe the bug**
The time-switch node is not displaying any status information.

**To Reproduce**
I have 4 nodes. Initally, I started with 2. They displayed their status OK. I then modified my flow further and added 2 more time-switch nodes. I have a fairly large set of flows with some other contrib nodes. Now, none of the time-switch nodes display any status. I have restarted the flows and restarted node-red.

**Expected behavior**
I expected all 4 time-switch nodes to display their status.

**Screenshots**
![image](https://user-images.githubusercontent.com/28573604/99834715-89de5600-2b5b-11eb-8b17-4459aefc3606.png)

**Environment (please complete the following information):**
 - OS: Raspbian Buster
 - Browser: Chrome on Windows 10
 - Version: Latest N-R

**Comment by jerbzz** [comment]
The node only updates status when it receives a message.
Perhaps it could update itself on flow restart or on a schedule?

**Comment by ghost** [comment]
@jerbzz I can confirm this. The nodes never display the current status but instead show the status they had during the last execution of the node. That's how all node-red nodes behave, even the system nodes. I am not even sure if i could bypass this behavior.

You could add the "Inject" node shipped with node red at the beginning of the flow. It allows to define a schedule or trigger the flow by clicking on it. Note that it will start your flow so that it is not applicable in every case and only works if your last action can be executed multiple times.
