### ISSUE TITLE
Config node for longitude/latitude settings

### ISSUE THREAD

**Issue by deosrc** [huzergackl/node-red-contrib-time-switch#13]
**Is your feature request related to a problem? Please describe.**

I recently updated this module from an older version (not sure which version) and have found that my flows are now failing due to missing longitude/latitude settings. I can go through and add the values but doing this on every node when they are the same value is cumbersome.

**Describe the solution you'd like**

Add a config node where longitude and latitude can be configured rather than (or in addition to) configuring it on each node.

**Describe alternatives you've considered**

Inputting the value for each node.

**Comment by devRoemer** [comment]
It was just an upgrade related topic. In previous versions it was possible to have nodes without geo position. This could lead to unexpected results on using the sun position related times. In this version the positions are mandatory to avoid issues.

On creating new nodes the current geo location is set automatically so that there is no need to manually set the values on creating a node. Using this way a user has the possibility to use a different geo location per node.

Despite this a global config like the server config in the home assistant plugin would be great. It also has the possibility to select a geo location per node by selecting a value from a dropdown but the coordinates are configured globally and have a label.  If somebody wants to contribute a feature like this i am willing to merge it into the project.
