### ISSUE TITLE
start sunset end 10pm

### ISSUE THREAD

**Issue by bergjet** [huzergackl/node-red-contrib-time-switch#8]
V1.0.4
Here the timer switches from sunset to 10pm next day.
I want to switch from sunset to 10pm on the same day.

**Comment by ghost** [comment]
@bergjet I did a quick test and had a look into the unit tests. The described behavior only appeared if the end time is before the start time. Which start and end times are you seeing below the node?

Just to be sure: Did you enter the time in 24h format?
(instead of 10:00 it should be 22:00)

If my assumption is right i would suggest that i introduce a checkbox where it is possible to configure if the end time can switch to the next day or if the range just gets 0 then.

**Comment by bergjet** [comment]
Die Version 1.06 funktioniert nun gar nicht.
Version 1.06 now does not work at all.
Its now 22:30
[Look at the picture](https://www.dropbox.com/s/7ne3kh9iyb2it0e/Screenshot%202020-04-11%2022.25.55.png?dl=0).

**Comment by ghost** [comment]
the issue related to the end time is fixed now. I will take a closer look at the sunset logic.
A library update might have introduced a change here

**Comment by ghost** [comment]
Fixed with 1.0.8.

**First flow**: End is before start - Assuming that the end is wished on the next day
**Second flow**: Was outside of the range - The status line shows that the range is reached on Apr 13th
**Third flow**: Was inside the range - Shows the end time of the active range

![grafik](https://user-images.githubusercontent.com/4304911/79080686-5ad74a80-7d17-11ea-877a-e81ecd07cffe.png)
